// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solution_bb_cpp
List solution_bb_cpp(NumericMatrix scores, IntegerVector capacities, NumericMatrix notes, NumericVector notes_min);
RcppExport SEXP _ParcoursupM2Algorithmique_solution_bb_cpp(SEXP scoresSEXP, SEXP capacitiesSEXP, SEXP notesSEXP, SEXP notes_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type capacities(capacitiesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type notes(notesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type notes_min(notes_minSEXP);
    rcpp_result_gen = Rcpp::wrap(solution_bb_cpp(scores, capacities, notes, notes_min));
    return rcpp_result_gen;
END_RCPP
}
// solution_dp_cpp
List solution_dp_cpp(NumericMatrix scores, IntegerVector capacities, NumericMatrix notes, NumericVector notes_min);
RcppExport SEXP _ParcoursupM2Algorithmique_solution_dp_cpp(SEXP scoresSEXP, SEXP capacitiesSEXP, SEXP notesSEXP, SEXP notes_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type capacities(capacitiesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type notes(notesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type notes_min(notes_minSEXP);
    rcpp_result_gen = Rcpp::wrap(solution_dp_cpp(scores, capacities, notes, notes_min));
    return rcpp_result_gen;
END_RCPP
}
// solution_greedy_cpp
List solution_greedy_cpp(NumericMatrix scores, IntegerVector capacities, NumericMatrix notes, NumericVector notes_min);
RcppExport SEXP _ParcoursupM2Algorithmique_solution_greedy_cpp(SEXP scoresSEXP, SEXP capacitiesSEXP, SEXP notesSEXP, SEXP notes_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type capacities(capacitiesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type notes(notesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type notes_min(notes_minSEXP);
    rcpp_result_gen = Rcpp::wrap(solution_greedy_cpp(scores, capacities, notes, notes_min));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ParcoursupM2Algorithmique_solution_bb_cpp", (DL_FUNC) &_ParcoursupM2Algorithmique_solution_bb_cpp, 4},
    {"_ParcoursupM2Algorithmique_solution_dp_cpp", (DL_FUNC) &_ParcoursupM2Algorithmique_solution_dp_cpp, 4},
    {"_ParcoursupM2Algorithmique_solution_greedy_cpp", (DL_FUNC) &_ParcoursupM2Algorithmique_solution_greedy_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ParcoursupM2Algorithmique(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
