# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solution_bb_cpp <- function(scores, capacities, notes, notes_min) {
    .Call(`_ParcoursupM2Algorithmique_solution_bb_cpp`, scores, capacities, notes, notes_min)
}

solution_dp_cpp <- function(scores, capacities, notes, notes_min) {
    .Call(`_ParcoursupM2Algorithmique_solution_dp_cpp`, scores, capacities, notes, notes_min)
}

solution_greedy_cpp <- function(scores, capacities, notes, notes_min) {
    .Call(`_ParcoursupM2Algorithmique_solution_greedy_cpp`, scores, capacities, notes, notes_min)
}

